### ISSUE TITLE
Create Results page js script

### ISSUE THREAD

**Issue by Mohlenkamp** [dorler/MartiansOnly#4]
Using local storage and any data passed from the search page, the script should process the users personal information, store the data in local storage and generate a boarding pass with any relevant information.

In addition, API calls may be needed to the NASA api to show martian weather or pictures of the target location.

**Comment by Mohlenkamp** [comment]
created a skeleton mock results page for you to get started doing some of the javascript work. It doesn't include the form for user data input (yet), but you can at least get a start getting some of the work underway.

**Comment by Miguel-Con-Queso** [comment]
js Results created
