### ISSUE TITLE
Create Slide Deck for presentation on Wednesday

### ISSUE THREAD

**Issue by Mohlenkamp** [dorler/MartiansOnly#5]
Self explanatory.  We all need to work on creating slide(s) for our topic areas.

This should also set our order of presentation. A run-through and publish should happen beforehand.

**Comment by dorler** [comment]
I have created an outline in google-slides. The link is : https://docs.google.com/presentation/d/1IODfUxOzCLFb650dL29PliyHnTwhKdDlkxF7N0HKrAo/edit?usp=sharing 

If you need access please message me your email. 

But we can also work on this Tuesday evening.

**Comment by Miguel-Con-Queso** [comment]
Presentation done
